// <auto-generated />
using System;
using EntityFrameworkCoreRelationships;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkCoreRelationships.Migrations
{
    [DbContext(typeof(Relationships))]
    partial class RelationshipsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EntityFrameworkCoreRelationships.Hierarchical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Hierarchicals");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.ManyToManyLeft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ManyToManyLefts");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.ManyToManyRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ManyToManyRelationships");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.ManyToManyRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ManyToManyRights");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.ManyToManyWithModeledLeft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelationshipId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipId");

                    b.ToTable("ManyToManyWithModeledLefts");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.ManyToManyWithModeledRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelationshipId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipId");

                    b.ToTable("ManyToManyWithModeledRights");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.NotRelated", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NotRelateds");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToMany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OneToManys");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToManyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OneToManyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OneToManyId");

                    b.ToTable("OneToManyItems");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToManyOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OneToManyOwners");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToOneLeft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OneToOneRightId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RightId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RightId");

                    b.ToTable("OneToOneLefts");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToOneOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OneToOneOwners");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToOneRight", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OneToOneLeftId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OneToOneRights");
                });

            modelBuilder.Entity("ManyToManyLeftManyToManyRight", b =>
                {
                    b.Property<int>("LeftsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeftsId", "RightsId");

                    b.HasIndex("RightsId");

                    b.ToTable("ManyToManyLeftManyToManyRight");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.Hierarchical", b =>
                {
                    b.HasOne("EntityFrameworkCoreRelationships.Hierarchical", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.ManyToManyWithModeledLeft", b =>
                {
                    b.HasOne("EntityFrameworkCoreRelationships.ManyToManyRelationship", "Relationship")
                        .WithMany("Lefts")
                        .HasForeignKey("RelationshipId");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.ManyToManyWithModeledRight", b =>
                {
                    b.HasOne("EntityFrameworkCoreRelationships.ManyToManyRelationship", "Relationship")
                        .WithMany("Rights")
                        .HasForeignKey("RelationshipId");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToManyItem", b =>
                {
                    b.HasOne("EntityFrameworkCoreRelationships.OneToMany", "OneToMany")
                        .WithMany("Items")
                        .HasForeignKey("OneToManyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OneToMany");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToManyOwner", b =>
                {
                    b.OwnsMany("EntityFrameworkCoreRelationships.OneToManyOwnedItem", "Items", b1 =>
                        {
                            b1.Property<int>("OneToManyOwnerId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.HasKey("OneToManyOwnerId", "Id");

                            b1.ToTable("OneToManyOwnedItem");

                            b1.WithOwner()
                                .HasForeignKey("OneToManyOwnerId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToOneLeft", b =>
                {
                    b.HasOne("EntityFrameworkCoreRelationships.OneToOneRight", "Right")
                        .WithMany()
                        .HasForeignKey("RightId");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToOneOwner", b =>
                {
                    b.OwnsOne("EntityFrameworkCoreRelationships.OneToOneOwned", "Owned", b1 =>
                        {
                            b1.Property<int>("OneToOneOwnerId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT");

                            b1.HasKey("OneToOneOwnerId");

                            b1.ToTable("OneToOneOwners");

                            b1.WithOwner()
                                .HasForeignKey("OneToOneOwnerId");
                        });

                    b.Navigation("Owned");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToOneRight", b =>
                {
                    b.HasOne("EntityFrameworkCoreRelationships.OneToOneLeft", "Left")
                        .WithOne()
                        .HasForeignKey("EntityFrameworkCoreRelationships.OneToOneRight", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Left");
                });

            modelBuilder.Entity("ManyToManyLeftManyToManyRight", b =>
                {
                    b.HasOne("EntityFrameworkCoreRelationships.ManyToManyLeft", null)
                        .WithMany()
                        .HasForeignKey("LeftsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkCoreRelationships.ManyToManyRight", null)
                        .WithMany()
                        .HasForeignKey("RightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.Hierarchical", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.ManyToManyRelationship", b =>
                {
                    b.Navigation("Lefts");

                    b.Navigation("Rights");
                });

            modelBuilder.Entity("EntityFrameworkCoreRelationships.OneToMany", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
